### ISSUE TITLE
Renaming a class retains the file with the old name

### ISSUE THREAD

**Issue by coolsquid** [OpenModLoader/Enigma#4]
It does create the new file, but also keeps the old one. This causes an error at launch, as Enigma doesn't allow duplicate mappings.

**Comment by lclc98** [comment]
I will delete all folders/files in mapping folder and generate them all back

**Comment by darkhax** [comment]
This issue still persists.

**Comment by lclc98** [comment]
It should be deleting the folder

**Comment by darkhax** [comment]
If you map a class as NameA and later rename it to NameB it will create a new mapping with the name NameB, but it will not delete NameA so you will have to mappings for the same class.
