### ISSUE TITLE
If you ignore an error, closing Enigma later doesn't actually close it

### ISSUE THREAD

**Issue by coolsquid** [OpenModLoader/Enigma#5]
It remains active in the background, using ~1gb of RAM.

**Comment by lclc98** [comment]
Wait, really?

**Comment by lclc98** [comment]
I cant confirm this

**Comment by coolsquid** [comment]
To reproduce: make a copy of any mapping file anywhere in the mapping directory. You'll now get a duplicate mappings error when you open the mappings. If you click ignore, you can't fully close Enigma later without using task manager.

[This](https://i.imgur.com/Yd7DXIw.png) is Enigmas memory usage, even though I don't have any instances open.

**Comment by darkhax** [comment]
I had this issue earlier but couldn't work out how to reproduce it.

**Comment by lclc98** [comment]
It should be fixed now
